src/Entity/JobOffer.php
<?php

namespace App\Entity;

use App\Repository\JobOfferRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobOfferRepository::class)]
class JobOffer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_active = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(length: 255)]
    private ?string $job_title = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $closing_date = null;

    #[ORM\Column]
    private ?int $salary = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $created_date = null;

    #[ORM\OneToMany(targetEntity: JobToCandidat::class, mappedBy: 'id_JobOffer')]
    private Collection $jobToCandidats;

    #[ORM\ManyToOne(inversedBy: 'JobOffer')]
    private ?Category $id_category = null;

    #[ORM\ManyToOne(inversedBy: 'jobOffer')]
    private ?JobType $id_JobType = null;

    #[ORM\ManyToOne(inversedBy: 'jobOffers')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $client = null;

    public function __construct()
    {
        $this->jobToCandidats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): static
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->job_title;
    }

    public function setJobTitle(string $job_title): static
    {
        $this->job_title = $job_title;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getClosingDate(): ?\DateTimeInterface
    {
        return $this->closing_date;
    }

    public function setClosingDate(?\DateTimeInterface $closing_date): static
    {
        $this->closing_date = $closing_date;

        return $this;
    }

    public function getSalary(): ?int
    {
        return $this->salary;
    }

    public function setSalary(int $salary): static
    {
        $this->salary = $salary;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(?\DateTimeInterface $created_date): static
    {
        $this->created_date = $created_date;

        return $this;
    }

    /**
     * @return Collection<int, JobToCandidat>
     */
    public function getJobToCandidats(): Collection
    {
        return $this->jobToCandidats;
    }

    public function addJobToCandidat(JobToCandidat $jobToCandidat): static
    {
        if (!$this->jobToCandidats->contains($jobToCandidat)) {
            $this->jobToCandidats->add($jobToCandidat);
            $jobToCandidat->setIdJobOffer($this);
        }

        return $this;
    }

    public function removeJobToCandidat(JobToCandidat $jobToCandidat): static
    {
        if ($this->jobToCandidats->removeElement($jobToCandidat)) {
            // set the owning side to null (unless already changed)
            if ($jobToCandidat->getIdJobOffer() === $this) {
                $jobToCandidat->setIdJobOffer(null);
            }
        }

        return $this;
    }

    public function getIdCategory(): ?Category
    {
        return $this->id_category;
    }

    public function setIdCategory(?Category $id_category): static
    {
        $this->id_category = $id_category;

        return $this;
    }

    public function getIdJobType(): ?JobType
    {
        return $this->id_JobType;
    }

    public function setIdJobType(?JobType $id_JobType): static
    {
        $this->id_JobType = $id_JobType;

        return $this;
    }

     public function __toString(): string
    {
        return $this->reference;
    }

     public function getClient(): ?Client
     {
         return $this->client;
     }

     public function setClient(?Client $client): static
     {
         $this->client = $client;

         return $this;
     }

}

src/Entity/JobToCandidat.php
<?php

namespace App\Entity;

use App\Repository\JobToCandidatRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobToCandidatRepository::class)]
class JobToCandidat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'jobToCandidats')]
    #[ORM\JoinColumn(nullable: false)]
    private ?JobOffer $id_JobOffer = null;

    #[ORM\ManyToOne(inversedBy: 'jobToCandidats')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Candidats $id_Candidat = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $time = null;

    #[ORM\Column(type: Types::BOOLEAN, nullable: true)]
    private ?bool $is_approved = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdJobOffer(): ?JobOffer
    {
        return $this->id_JobOffer;
    }

    public function setIdJobOffer(?JobOffer $id_JobOffer): static
    {
        $this->id_JobOffer = $id_JobOffer;

        return $this;
    }

    public function getIdCandidat(): ?Candidats
    {
        return $this->id_Candidat;
    }

    public function setIdCandidat(?Candidats $id_Candidat): static
    {
        $this->id_Candidat = $id_Candidat;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime(?\DateTimeInterface $time): static
    {
        $this->time = $time;

        return $this;
    }

    public function isIsApproved(): ?bool
    {
        return $this->is_approved;
    }

    public function setIsApproved(bool $is_approved): static
    {
        $this->is_approved = $is_approved;

        return $this;
    }
}

src/Form/JobOfferType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\JobOffer;
use App\Entity\JobType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JobOfferType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reference')
            ->add('description')
            ->add('is_active')
            ->add('notes')
            ->add('job_title')
            ->add('location')
            ->add('closing_date', null, [
                'widget' => 'single_text',
            ])
            ->add('salary')
            ->add('created_date', null, [
                'widget' => 'single_text',
            ])
            ->add('id_category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'id',
            ])
            ->add('id_JobType', EntityType::class, [
                'class' => JobType::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => JobOffer::class,
        ]);
    }
}

src/Controller/JobOfferController.php
<?php

namespace App\Controller;

use App\Entity\JobOffer;
use App\Form\JobOfferType;
use App\Repository\JobOfferRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/job/offer')]
class JobOfferController extends AbstractController
{
    #[Route('/', name: 'app_job_offer_index', methods: ['GET'])]
    public function index(JobOfferRepository $jobOfferRepository): Response
    {

        $user = $this->getUser();


        if ($user) {
            
            $candidats_Id = $user->getCandidats()->getId();
        }

        return $this->render('job_offer/index.html.twig', [
            'job_offers' => $jobOfferRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_job_offer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $jobOffer = new JobOffer();
        $form = $this->createForm(JobOfferType::class, $jobOffer);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($jobOffer);
            $entityManager->flush();

            return $this->redirectToRoute('app_job_offer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('job_offer/new.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_job_offer_show', methods: ['GET'])]
    public function show(Request $request, JobOffer $jobOffer): Response
    {
        return $this->render('job_offer/show.html.twig', [
            'job' => $jobOffer,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_job_offer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, JobOffer $jobOffer, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(JobOfferType::class, $jobOffer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_job_offer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('job_offer/edit.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_job_offer_delete', methods: ['POST'])]
    public function delete(Request $request, JobOffer $jobOffer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$jobOffer->getId(), $request->request->get('_token'))) {
            $entityManager->remove($jobOffer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_job_offer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/job_offer/_delete_form.html.twig
<form method="post" action="{{ path('app_job_offer_delete', {'id': job_offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ job_offer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/job_offer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit JobOffer{% endblock %}

{% block body %}
    <h1>Edit JobOffer</h1>

    {{ include('job_offer/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_job_offer_index') }}">back to list</a>

    {{ include('job_offer/_delete_form.html.twig') }}
{% endblock %}

templates/job_offer/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    
<div class="base">

    <!-- Page -->
    <div class="page">

        <!-- Page Header-->
        <section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="white-text">Our job offers</h2>
                        <span class="white-text">Search and filter by job category</span>
                        
                    </div>
                </div>
            </div>
        </section>


        <!-- Page Content-->
        <section id="job-offers" class="section-padding gray-bg">
            <div class="container">
                <div class="text-center mb-40">
                    <h2 class="section-title">We have the perfect job for you</h2>
                    <p class="section-sub">just like our candidates, we offer quality, serious & reliable job offers.</p>
                </div>
                <div class="portfolio-container">

                    <ul class="portfolio-filter brand-filter text-center">
                        <li class="active waves-effect waves-light" data-group="all">All</li>
                        <li class=" waves-effect waves-light" data-group="commercial">Commercial</li>
                        <li class=" waves-effect waves-light" data-group="retail">Retail sales</li>
                        <li class=" waves-effect waves-light" data-group="creative">Creative</li>
                        <li class=" waves-effect waves-light" data-group="technology">Technology</li>
                        <li class=" waves-effect waves-light" data-group="marketing">Marketing & PR</li>
                        <li class=" waves-effect waves-light" data-group="fashion">Fashion & luxury</li>
                        <li class=" waves-effect waves-light" data-group="management">Management & HR</li>
                    </ul>
                    <div class="portfolio portfolio-with-title col-2 gutter mt-30">

                         {% for job in job_offers %}

                        <div class="portfolio-item" data-groups='["all", "{{ job.idJobType.type }}"]'>
                            <div class="portfolio-wrapper">
                                <div class="card job-card">
                                    <div class="card-content">
                                        <span class="title">
                                            <span class="card-title">{{ job.jobtitle }}</span>
                                            <span class="ref grey-text">{{ job.reference }}</span>
                                        </span>
                                        <div class="metas mb-20">
                                            <div class="meta">
                                                <i class="material-icons">&#xE53E;</i>{{ job.salary }}&euro;
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE916;</i>{{ job.createddate|date("m/d/Y") }}
                                            </div>
                                            <div class="meta">
                                                <i class="material-icons">&#xE55F;</i>{{ job.location }}
                                            </div>
                                        </div>
                                        <p class="truncate-text">{{ job.description|slice(0, 40) }}</p>
                                    </div>
                                    <div class="card-action">
                                        <a class="btn btn-md primary border waves-effect waves-dark"
                                            href="{{ path('app_job_offer_show', {'id': job.id}) }}">Details</a>
                                    {% if app.user %}
                                    
                                        {% if app.user.candidats.Completion == 100 %}
                                            <form action="{{ path('app_job_to_candidat_new') }}" method="post">
                                                <button type="submit" id="Apply" class="btn btn-md primary waves-effect waves-light">Apply</button>
                                                <input type="hidden" name="jobOffer_ID" value="{{ job.id }}" >
                                            </form>
                                        {% else %}
                                            <button type="submit" id="Apply" class="">Apply</button>
                                        {% endif %}
                                    
                                    {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                        <div class="no-item"></div>
                    </div>
                </div>
            </div>
        </section>

        <section class="cta-candidate bg-fixed bg-cover overlay dark-5 padding-top-70 padding-bottom-50">
            <div class="container">
                <div class="row">
                    <div class="valign-wrapper text-center">
                        <div class="hero-intro valign-cell">
                            <h2 class="tt-headline clip is-full-width no-margin">
                                <span>You are </span>
                                <span class="tt-words-wrapper">
                                    <b class="is-visible">Commercial</b>
                                    <b>Creative</b>
                                    <b>Marketing & PR</b>
                                    <b>Technology</b>
                                    <b>Fashion & luxury</b>
                                    <b>Retail sales</b>
                                </span>
                            </h2>
                            <h3 class="c-secondary mb-30 no-margin">Sign-up and apply for jobs now</h3>
                            <p class="white-text section-sub">Each one of your skills is seen as precious resource to us, each one of your personality traits are considered as an added on value. Joining us is allowing our recruitment expertise and personal guidance to bring the best out in you by choosing the most suited position.</p>

                            <a href="{{ path('app_login') }}" class="btn border secondary waves-effect waves-light mt-40">Join us</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </div>

</div>

{% endblock %}

templates/job_offer/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New JobOffer{% endblock %}

{% block body %}
    <h1>Create new JobOffer</h1>

    {{ include('job_offer/_form.html.twig') }}

    <a href="{{ path('app_job_offer_index') }}">back to list</a>
{% endblock %}

templates/job_offer/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   
{# <pre>
    {{ dump(job) }}
</pre> #}

<div class="base">

    <!-- Page -->
    <div class="page">

        <!-- Page Header-->
        <section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="white-text">{{ job.jobtitle }}</h2>
                        <span class="white-text">{{ job.reference }}</span>
                        <ol class="breadcrumb">
                            <li>
                                <div class="portfolio-nav">
                                    <a href="{{ path('app_job_offer_show', {'id': job.id - 1}) }}" class="waves-effect waves-dark"><i class="fa fa-angle-left" aria-hidden="true"></i> Prev</a>
                                    <a href="{{ path('app_job_offer_index') }}" class="waves-effect waves-dark"><i class="fa fa-th-large" aria-hidden="true"></i></a>
                                    <a href="{{ path('app_job_offer_show', {'id': job.id + 1}) }}" class="waves-effect waves-dark">Next <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                </div>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        <!-- Page Content-->
        <section class="single-project-section section-padding light-gray-bg">
            <div class="container">
                <div class="project-overview">
                    <div class="row mb-80">
                        <div class="col-xs-12 col-md-8">
                            <p class="ref grey-text no-margin">{{ job.reference }}</p>
                            <h2>{{ job.jobtitle }}</h2>
                            <p>{{ job.description }}</p>
                        </div>

                        <div class="col-xs-12 col-md-4 quick-overview">
                            <ul class="portfolio-meta">
                                <li><span> Pulished at </span>{{ job.createddate|date("m/d/Y") }}</li>
                                <li><span> Position </span>{{ job.jobtitle }}</li>
                                <li><span> Contract Type </span>{{ job.idcategory }}</li>
                                <li><span> Salary </span>{{ job.salary }} &euro;</li>
                                <li><span> Location </span>{{ job.location }}</li>
                                <li><span> Starting date </span>{{ job.closingdate|date("m/d/Y") }}</li>
                            </ul>

                            {% if app.user %}
                            
                                {% if app.user.candidats.Completion == 100 %}
                                            <form action="{{ path('app_job_to_candidat_new') }}" method="post">
                                                <button type="submit" id="Apply" class="btn btn-md primary waves-effect waves-light">Apply</button>
                                                <input type="hidden" name="jobOffer_ID" value="{{ job.id }}" >
                                            </form>
                                        {% else %}
                                            <button type="submit" id="Apply" class="">Apply</button>
                                {% endif %}

                                
                
                                {% for candidature in app.user.candidats.jobToCandidats %}        
                                    {% if candidature.idJobOffer.id == job.id %}
                                        <div class="btn btn-block btn-danger mt-30 waves-effect waves-light disabled" style="color: white;">You have already applied</div>
                                    {% else %}
                                        <div class="btn btn-block btn-success mt-30 waves-effect waves-light disabled">You can applied for this job</div>
                                    {% endif %}
                                
                                {% endfor %}

                            {% endif %}
                        </div>
                    </div>
                </div>

                
           

                <nav class="single-post-navigation no-margin" role="navigation">
                    <div class="row">

                        <div class="col-xs-6 col-sm-6 col-md-4">
                            <div class="previous-post-link">
                                <a class="btn border primary waves-effect waves-dark" href="{{ path('app_job_offer_show', {'id': job.id - 1}) }}">
                                    <i class="fa fa-long-arrow-left"></i>Previous
                                </a>
                            </div>
                        </div>
                        <div class="hidden-xs hidden-sm col-md-4"></div>


                        <div class="col-xs-6 col-sm-6 col-md-4">
                            <div class="next-post-link">
                                <a class="btn border primary waves-effect waves-dark" href="{{ path('app_job_offer_show', {'id': job.id + 1}) }}">
                                    Next <i class="fa fa-long-arrow-right"></i>
                                </a>
                            </div>
                        </div>

                    </div>
                </nav>
            </div>
        </section>

    </div>

</div>

{% endblock %}