src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $society_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $activitie_type = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $poste = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_number = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $notes = null;

    #[ORM\OneToMany(targetEntity: JobOffer::class, mappedBy: 'client')]
    private Collection $jobOffers;

    public function __construct()
    {
        $this->jobOffers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSocietyName(): ?string
    {
        return $this->society_name;
    }

    public function setSocietyName(string $society_name): static
    {
        $this->society_name = $society_name;

        return $this;
    }

    public function getActivitieType(): ?string
    {
        return $this->activitie_type;
    }

    public function setActivitieType(?string $activitie_type): static
    {
        $this->activitie_type = $activitie_type;

        return $this;
    }

    public function getContactName(): ?string
    {
        return $this->contact_name;
    }

    public function setContactName(string $contact_name): static
    {
        $this->contact_name = $contact_name;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->poste;
    }

    public function setPoste(?string $poste): static
    {
        $this->poste = $poste;

        return $this;
    }

    public function getContactNumber(): ?string
    {
        return $this->contact_number;
    }

    public function setContactNumber(string $contact_number): static
    {
        $this->contact_number = $contact_number;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(string $contact_email): static
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    /**
     * @return Collection<int, JobOffer>
     */
    public function getJobOffers(): Collection
    {
        return $this->jobOffers;
    }

    public function addJobOffer(JobOffer $jobOffer): static
    {
        if (!$this->jobOffers->contains($jobOffer)) {
            $this->jobOffers->add($jobOffer);
            $jobOffer->setClient($this);
        }

        return $this;
    }

    public function removeJobOffer(JobOffer $jobOffer): static
    {
        if ($this->jobOffers->removeElement($jobOffer)) {
            // set the owning side to null (unless already changed)
            if ($jobOffer->getClient() === $this) {
                $jobOffer->setClient(null);
            }
        }

        return $this;
    }


    public function __toString(): string
    {
        return $this->society_name;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('society_name')
            ->add('activitie_type')
            ->add('contact_name')
            ->add('poste')
            ->add('contact_number')
            ->add('contact_email')
            ->add('notes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/client')]
class ClientController extends AbstractController
{
    #[Route('/', name: 'app_client_index', methods: ['GET'])]
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_client_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_client_show', methods: ['GET'])]
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_client_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Client $client, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_client_delete', methods: ['POST'])]
    public function delete(Request $request, Client $client, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('app_client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn">Delete</button>
</form>

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Client{% endblock %}

{% block body %}
    <h1>Edit Client</h1>

    {{ include('client/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_client_index') }}">back to list</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client index{% endblock %}

{% block body %}
    <h1>Client index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Society_name</th>
                <th>Activitie_type</th>
                <th>Contact_name</th>
                <th>Poste</th>
                <th>Contact_number</th>
                <th>Contact_email</th>
                <th>Notes</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.societyName }}</td>
                <td>{{ client.activitieType }}</td>
                <td>{{ client.contactName }}</td>
                <td>{{ client.poste }}</td>
                <td>{{ client.contactNumber }}</td>
                <td>{{ client.contactEmail }}</td>
                <td>{{ client.notes }}</td>
                <td>
                    <a href="{{ path('app_client_show', {'id': client.id}) }}">show</a>
                    <a href="{{ path('app_client_edit', {'id': client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_client_new') }}">Create new</a>
{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Client{% endblock %}

{% block body %}
    <h1>Create new Client</h1>

    {{ include('client/_form.html.twig') }}

    <a href="{{ path('app_client_index') }}">back to list</a>
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client{% endblock %}

{% block body %}
    <h1>Client</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Society_name</th>
                <td>{{ client.societyName }}</td>
            </tr>
            <tr>
                <th>Activitie_type</th>
                <td>{{ client.activitieType }}</td>
            </tr>
            <tr>
                <th>Contact_name</th>
                <td>{{ client.contactName }}</td>
            </tr>
            <tr>
                <th>Poste</th>
                <td>{{ client.poste }}</td>
            </tr>
            <tr>
                <th>Contact_number</th>
                <td>{{ client.contactNumber }}</td>
            </tr>
            <tr>
                <th>Contact_email</th>
                <td>{{ client.contactEmail }}</td>
            </tr>
            <tr>
                <th>Notes</th>
                <td>{{ client.notes }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_client_index') }}">back to list</a>

    <a href="{{ path('app_client_edit', {'id': client.id}) }}">edit</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}